# Generated by Django 3.2 on 2022-05-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_expert', models.BooleanField(default=False, verbose_name='is active expert')),
                ('ready_to_serve', models.BooleanField(default=False, verbose_name='ready to serve')),
                ('ready_to_serve_expire_time', models.DateTimeField(auto_now=True, verbose_name='ready to serve expire time')),
                ('father_name', models.CharField(max_length=26, null=True, verbose_name='father name')),
                ('shaba_numer', models.CharField(max_length=24, verbose_name='shaba number')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('military_service', models.IntegerField(blank=True, choices=[(1, 'WOMEN'), (2, 'DONE'), (3, 'EXEMPT'), (4, 'SUBJECT')], null=True, verbose_name='military service')),
                ('married_status', models.IntegerField(choices=[(1, 'SINGLE'), (2, 'MARRIED')], verbose_name='married status')),
                ('insuranceID', models.CharField(max_length=32, verbose_name='insuranceID')),
                ('score_expert', models.IntegerField(default=0, verbose_name='score expert')),
                ('total_profit', models.IntegerField(default=0, verbose_name='total profit')),
                ('expert_balance', models.IntegerField(default=0, verbose_name='expert balance')),
                ('free_expert_balance', models.IntegerField(default=0, verbose_name='free expert balance')),
                ('country', models.CharField(default='iran', max_length=32, verbose_name='country')),
                ('state', models.CharField(max_length=12, verbose_name='state')),
                ('city', models.CharField(max_length=12, verbose_name='city')),
                ('address', models.TextField(verbose_name='address')),
                ('count_complete_services', models.PositiveIntegerField(default=0, verbose_name='count complete services')),
                ('latitude', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=16, default=0, max_digits=19, verbose_name='longitude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
