# Generated by Django 3.2 on 2022-05-26 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_number', models.CharField(default='+98', max_length=5, verbose_name='sub number')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile')),
                ('nationality_code', models.CharField(max_length=12, unique=True, verbose_name='nationality code')),
                ('nationality', models.IntegerField(choices=[(1, 'IRAN'), (2, 'AFGHANISTAN'), (3, 'OTHER')], default=1, verbose_name='nationality')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'MALE'), (2, 'FEMALE')], null=True, verbose_name='gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/profile_image', verbose_name='profile image')),
                ('profile_thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=10, size=[515, 478], upload_to='user/profile_thumbnail')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('friend_counts', models.PositiveIntegerField(default=0, verbose_name='friend counts')),
                ('count_receive_services', models.PositiveIntegerField(default=0, verbose_name='count receive services')),
                ('otp_password', models.CharField(blank=True, max_length=6, null=True, verbose_name='otp password')),
                ('otp_time_created', models.DateTimeField(auto_now_add=True, verbose_name='otp created time')),
                ('otp_expire_time', models.DateTimeField(default=datetime.datetime(2022, 5, 26, 13, 46, 59, 377799), verbose_name='otp expire time')),
                ('is_active_customer', models.BooleanField(default=True, verbose_name='is active customer')),
                ('is_expert', models.BooleanField(default=False, verbose_name='is expert')),
                ('wallet_balance', models.IntegerField(default=0, verbose_name='wallet balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
