# Generated by Django 3.2 on 2022-05-27 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 18, 16, 30, 302821), verbose_name='otp expire time'),
        ),
    ]
